[project]
name = "deep-learning-mit"
version = "0.1.0"
description = "Nothing"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=5.0.0",
    "deepinv>=0.4.1",
    "einops>=0.8.2",
    "graphviz>=0.21",
    "matplotlib>=3.10.8",
    "torch>=2.11.0",
    "torchview>=0.2.7",
    "torchvision>=0.26.0",
    "tqdm>=4.67.3",
]
